name: Check Macaulay2 MRDI package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mrdi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Macaulay2
        run: |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2
          sudo apt-get -y install macaulay2

      - name: Install MRDI package
        run: M2 -e 'installPackage("MRDI", FileName => "m2/MRDI.m2"); exit 0'

      - name: Check MRDI package
        run: M2 -e 'check "MRDI"; exit 0'
